.firebaserc
.github/workflows/ci.yml
package.json
rundev.js
src/config.js

Rename preview to staging everywhere

---

functions/src/index.ts

Apparently, transaction handlers are very often called with null even if
the object exists as an optimization. See:
https://groups.google.com/g/firebase-talk/c/Lyb0KlPdQEo
https://stackoverflow.com/a/65415636/5190601
Also, use server-side increment in createGame.
Fixes: https://github.com/eltoder/setwithfriends/issues/4

Fix NPE in finishGame

---

functions/src/index.ts

Improve transaction logic in finishGame

---

database.rules.json

Enforce ban status in db rules

---

src/components/GameInfoRow.js
src/pages/ProfilePage.js

Don't crash on missing games

---

src/components/ProfileName.js

Because changing color is a free feature now.

Add a button to reset user's color

---

.github/dependabot.yml
src/util.js

Use asterisks for censoring

---

src/components/Chat.js
src/hooks/useStats.js

Require playing 3 games before posting in lobby chat

---

src/components/Chat.js
src/hooks/useFirebaseQuery.js
src/pages/LobbyPage.js

Make the chat bigger on bigger screens.

Change lobby layout

---

database.rules.json
functions/src/game.ts
src/components/ChatCards.js
src/components/GameSettings.js
src/pages/GamePage.js
src/util.js

Add ultra9 game mode

---

src/util.js

Reduce movement of cards

---

src/util.js

the newest cards are always in the bottom row. One of them must be a member of the SET.

Make sure if the board is expanded

---

src/components/Chat.js
src/pages/LobbyPage.js

Also, always scroll to bottom on enter.
Also, use the left border for mentions like on discord.

Don't send whitespace-only messages

---

database.rules.json
src/components/Chat.js
src/components/ChatCards.js
src/components/Game.js
src/pages/GamePage.js
src/pages/LobbyPage.js
src/pages/RoomPage.js

Also, add space as another hotkey to clear selection.

Add hotkeys for new game/start game/play again

---

functions/src/game.ts
src/game.js
src/game.test.js
src/pages/GamePage.js

Also remove some code duplication.

Remove unnecessary assumptions

---

src/components/Chat.js
src/components/ResponsiveSetCard.js
src/pages/GamePage.js
src/pages/RoomPage.js

* Don't highlight hovered cards on mobile
* A hotkey to quit game: Ctrl+Q
* Timestamps in game room chat

Minor UI updates

---

src/components/Game.js
src/components/ResponsiveSetCard.js
src/components/SetCard.js
src/game.js
src/pages/GamePage.js
src/themes.js

Switch MegaSet to border styles

---

package-lock.json
src/pages/HelpPage.js

Help page for Junior, Ultra9, MegaSet, GhostSet

---

functions/src/game.ts
src/components/Game.js
src/game.js
src/game.test.js
src/pages/GamePage.js
src/pages/HelpPage.js

Memoize findSet in GamePage

---

src/components/Chat.js
src/utils/autoscroll.js

Also, debounce onScroll event handler.

Replace js code with css scroll-behavior: smooth

---

src/components/Chat.js
src/utils/autoscroll.js

Reverts eltoder/setwithfriends#105

Revert "Replace js code with css scroll-behavior: smooth"

---

database.rules.json
functions/src/index.ts
src/components/GameSettings.js
src/components/GameSidebar.js
src/components/ProfileGamesTable.js
src/game.js
src/pages/GamePage.js
src/pages/LobbyPage.js
src/pages/ProfilePage.js

* Rename "enable hints" into "practice mode"
* Make hints work in multiplayer games
* Allow pausing practice games
* Show practice games in profiles with a practice icon
Closes: #50

Add practice mode

---

src/App.js
src/components/Navbar.js
src/pages/GamePage.js
src/pages/HelpPage.js
src/pages/LobbyPage.js
src/pages/RoomPage.js

And document them on the Help page.

Add shortcuts to change settings

---

src/components/Game.js
src/pages/GamePage.js

Also, make landscape layout a bit more usable on mobile.

Disable clicking on moving cards

---

database.rules.json
functions/src/game.ts
public/index.html
src/components/ResponsiveSetCard.js
src/components/SetCard.js
src/game.js

* Change shape and pattern
* Add junior mode

Puzzle mode tweaks

---

src/App.js
src/components/Navbar.js
src/pages/GamePage.js

Game notifications being the "Not a Set" and "Found a Set" messages and the corresponding sounds.
Closes:  #153

Added option to turn of game notifications
